#: import Window kivy.core.window.Window

<FlatButton@ButtonBehavior+Label>:
    text: 'default'
<AdminWindow>:
    id: main_win
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        id: top_nav
        size_hint_y: None
        height: 30
        canvas.before:
            Color:
                rgba: (.59, .20, .63,1)
            Rectangle:
                size: self.size
                pos: self.pos

        FlatButton:
            id: file_trigger
            text: 'File'
            on_release: file_dropdown.open(self)
            size_hint: (.1,None)
            height: 30

            Widget:
                on_parent: file_dropdown.dismiss()

                DropDown:
                    id: file_dropdown
                    Button:
                        id: close
                        text: 'Salir'
                        size_hint_y: None
                        height: 30
                        on_release: root.logout()
                    Button:
                        id: close
                        text: 'Cerrar'
                        size_hint_y: None
                        height: 30
                        on_release: Window.close()
        Label:
            text: 'Admin Dashboard'
            bold: True
            size_hint: (.9,None)
            height: 30
    BoxLayout:
        id: content_nav

        BoxLayout:
            id: nav_tabs
            size_hint_x: .2
            orientation: 'vertical'
            canvas.before:
                Color:
                    rgba: 0.50, 0.35, 0.55, 1
                Rectangle:
                    size: self.size
                    pos: self. pos
            ToggleButton:
                id: user_toggle
                text: 'Manage Users'
                size_hint_y: .1
                state: 'down'
                background_color: .80, .30, .80, 1
                background_normal: ''
                group:'admin_navs'
                on_state: root.change_screen(self)
            ToggleButton:
                id: products_toggle
                text: 'Manage Products'
                size_hint_y: .1
                background_color: .80, .30, .80, 1
                background_normal: ''
                group:'admin_navs'
                on_state: root.change_screen(self)
            ToggleButton:
                id: analysis_toggle
                text: 'Products Analysis'
                size_hint_y: .1
                background_color: .80, .30, .80, 1
                background_normal: ''
                group:'admin_navs'
                on_state: root.change_screen(self)
            Label:
                id:sp
                text: ''
                size_hint_y:.7
        BoxLayout:
            id: all_content
            size_hint_x: .8
            padding:(20, 10)
            ScreenManager:
                id: scrn_mngr
                Screen:
                    id: scrn_content
                    name: 'scrn_content'
                    BoxLayout:
                        orientation: 'vertical'
                        spacing: 10
                        BoxLayout:
                            id: scrn_contents
                        BoxLayout:
                            id: scrn_pax
                            # canvas:
                            #     Color:
                            #         rgb: 0,0,0
                            #     Rectangle:
                            #         size:self.size
                            #         pos: self.pos
                        BoxLayout:
                            id: ops_fields
                            spacing: 10
                            size_hint_y: None
                            height: 35
                        BoxLayout:
                            id: ops_btns
                            spacing: 10
                            size_hint_y: None
                            height: 45
                            Spinner:
                                id: target_user
                                text: 'Agregar'
                                values: ['Usuario','Paciente']
                                on_release: root.user_or_pax()
                            # Button:
                            #     id: target_user
                            #     text: 'Agregar'
                            #     on_release: file_dropdown2.open(self)
                            #     size_hint_y: (None)
                            #     height: 30
                            #
                            #     Widget:
                            #         on_parent: file_dropdown2.dismiss()
                            #
                            #         DropDown:
                            #             id: file_dropdown2
                            #             Button:
                            #                 text: 'Paciente'
                            #                 on_release: root.add_pax()
                            #                 # size_hint_y: None
                            #                 # height: 30
                            #             Button:
                            #                 text: 'Usuario'
                            #                 on_release: root.add_user()

                            Button:
                                id: crud_update
                                text: 'Modificar'
                                on_release: root.update_user_fields()
                            Button:
                                id: crud_remove
                                text: 'Eliminar'
                                on_release: root.remove_user_fields()
                Screen:
                    id: scrn_product_content
                    name: 'scrn_product_content'
                    BoxLayout:
                        orientation: 'vertical'
                        spacing: 10
                        BoxLayout:
                            id: scrn_product_contents
                        BoxLayout:
                            id: ops_fields_P
                            spacing: 10
                            size_hint_y: None
                            height: 35
                        BoxLayout:
                            id: ops_btns_P
                            spacing: 10
                            size_hint_y: None
                            height: 45
                            Button:
                                id: crud_add_P
                                text: 'Agregar'
                                on_release: root.add_product_fields()
                            Button:
                                id: crud_update_P
                                text: 'Modificar'
                                on_release: root.update_product_fields()
                            Button:
                                id: crud_remove_P
                                text: 'Eliminar'
                                on_release: root.remove_product_fields()
                Screen:
                    id: scrn_analysis
                    name: 'scrn_analysis'
                    BoxLayout:
                        orientation: 'vertical'
                        spacing: 10
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_y: None
                            height: 45
                            Spinner:
                                id: target_product
                                text: 'Choose Product'
